CONFIG_REMOTE=y
CONFIG_REMOTE_PROTOCOL_DT7=y
# CONFIG_REMOTE_PROTOCOL_VT13=y
CONFIG_CPP=y

# UART Configuration
CONFIG_UART_STM32=n
CONFIG_UART_STM32_FIX=y
CONFIG_UART_ASYNC_API=y

# RTT (Real-Time Transfer) Configuration
CONFIG_ASSERT=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

CONFIG_DCACHE=n

# Optional: Enable RTT logging backend
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
# CONFIG_REMOTE_LOG_LEVEL_DBG=y
CONFIG_LOG=y
