CONFIG_BREEZE=y
CONFIG_PRINTK=y

CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=4096
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n

# 保留基本优化但便于调试（ 如果不配置这一条可能导致代码被优化掉，断点无效 ）
CONFIG_DEBUG_OPTIMIZATIONS=y

# RTT->VOFA+ 配置
CONFIG_USE_SEGGER_RTT=y
# 5个上行通道 2个下行通道
CONFIG_SEGGER_RTT_MAX_NUM_UP_BUFFERS=5
CONFIG_SEGGER_RTT_MAX_NUM_DOWN_BUFFERS=2
